
tasks:
  - before: |
      nvm install --lts
      npx playwright install
      npx playwright install-deps
  - init: |
      nvm use --lts
      yarn install
    command: |
      nvm use --lts
      npx playwright test  --project="Mobile Chrome"

ports:
  - port: 9323
    name: Playwright Report
    visibility: public
