
tasks:
  - before: |
      nvm install --lts
  - init: |
      nvm use --lts
      yarn install
      yarn playwright install-deps
    command: |
      npx playwright test  --project="Mobile Chrome"

ports:
  - port: 9323
    name: Playwright Report
    visibility: public
