name: Playwright Setup

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies for all browsers
        run: npx playwright install-deps
      - name: Install dependencies for Chromium only
        run: npx playwright install-deps chromium
      - name: Run tests
        run: npm run test -- --testPathPattern=tests
